### ISSUE TITLE
simplewallet balance jack, Not working with the following error.

### ISSUE THREAD

**Issue by deusmachinea** [askmish/sawtooth-simplewallet#32]
root@d533a2567fd4:/project/simplewallet/pyclient# simplewallet balance jack #Displays the balance left in Jack's account
[19:48:16 INFO    connectionpool] Starting new HTTP connection (1): rest-api
[19:48:16 DEBUG   connectionpool] "GET /state/7e266409c158f073860c0938ce27c3eea1354b73d3313da10e46c6a828eac674bef285 HTTP/1.1" 404 134
Traceback (most recent call last):
  File "/project/simplewallet/pyclient/wallet/simplewallet_client.py", line 148, in _send_to_restapi
    result.status_code, result.reason))
Exception: Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/simplewallet/pyclient/wallet/simplewallet_cli.py", line 257, in main_wrapper
    main()
  File "/project/simplewallet/pyclient/wallet/simplewallet_cli.py", line 243, in main
    do_balance(args)
  File "/project/simplewallet/pyclient/wallet/simplewallet_cli.py", line 208, in do_balance
    data = client.balance()
  File "/project/simplewallet/pyclient/wallet/simplewallet_client.py", line 117, in balance
    "state/{}".format(self._address))
  File "/project/simplewallet/pyclient/wallet/simplewallet_client.py", line 155, in _send_to_restapi
    raise Exception(err)
Exception: Error 404: Not Found

**Comment by honeyjills** [comment]
Hey , This is happening when we are directly trying to figure out the balance  of the user before doing any transactions rght?

**Comment by askmish** [comment]
@kaali-python Could you respond if you face the issue still. or the behavior is as honeyjills had said in earlier comment?

**Comment by deusmachinea** [comment]
The issue has been resolved, @honeyjills  was right.

**Comment by askmish** [comment]
Glad to know that the issue has been resolved. I'll go ahead and close this issue.
